import { Asset, RiskItem } from '../types';

export const DENTAL_ASSETS_TEMPLATE = (clientId: string): Asset[] => [
  {
    id: 'da_samc_1',
    client_id: clientId,
    asset_code: 'AST-SRV-001',
    asset_name: 'PowerEdge R750xs',
    asset_type: 'IT Asset',
    asset_category: 'Server',
    asset_owner: 'IT Manager',
    classification: 'CONFIDENTIAL',
    location: 'Main Server Room Rack 1',
    status: 'ACTIVE',
    c_val: 4,
    i_val: 4,
    a_val: 4,
  },
  {
    id: 'da_samc_2',
    client_id: clientId,
    asset_code: 'AST-UPS-002',
    asset_name: 'Socomec',
    asset_type: 'IT Asset',
    asset_category: 'Other',
    asset_owner: 'IT Manager',
    classification: 'CONFIDENTIAL',
    location: 'Server Room UPS Station',
    status: 'ACTIVE',
    c_val: 4,
    i_val: 4,
    a_val: 4,
  },
  {
    id: 'da_samc_3',
    client_id: clientId,
    asset_code: 'AST-WS-003',
    asset_name: 'Precision 5820 Tower',
    asset_type: 'IT Asset',
    asset_category: 'Desktop',
    asset_owner: 'IT Manager',
    classification: 'INTERNAL',
    location: 'Clinical Workstation Desk A',
    status: 'ACTIVE',
    c_val: 4,
    i_val: 4,
    a_val: 4,
  },
  {
    id: 'da_samc_4',
    client_id: clientId,
    asset_code: 'AST-MED-004',
    asset_name: 'AUTOCLAVE',
    asset_type: 'Biomedical Asset',
    asset_category: 'Other',
    asset_owner: 'Clinic Manager',
    classification: 'RESTRICTED',
    location: 'Sterilization Room 1',
    status: 'ACTIVE',
    c_val: 5,
    i_val: 5,
    a_val: 5,
  },
  {
    id: 'da_samc_5',
    client_id: clientId,
    asset_code: 'AST-MED-005',
    asset_name: 'DENTAL CHAIR UNIT',
    asset_type: 'Biomedical Asset',
    asset_category: 'Other',
    asset_owner: 'Clinic Manager',
    classification: 'RESTRICTED',
    location: 'Dental Suite Operatory A',
    status: 'ACTIVE',
    c_val: 5,
    i_val: 5,
    a_val: 5,
  },
  {
    id: 'da_samc_6',
    client_id: clientId,
    asset_code: 'AST-MED-006',
    asset_name: 'ULTRASOUND',
    asset_type: 'Biomedical Asset',
    asset_category: 'Other',
    asset_owner: 'Clinic Manager',
    classification: 'CONFIDENTIAL',
    location: 'Imaging Room 1',
    status: 'ACTIVE',
    c_val: 4,
    i_val: 4,
    a_val: 4,
  },
  {
    id: 'da_samc_7',
    client_id: clientId,
    asset_code: 'AST-NAS-007',
    asset_name: 'TS-832PX',
    asset_type: 'IT Asset',
    asset_category: 'Server',
    asset_owner: 'IT Manager',
    classification: 'CONFIDENTIAL',
    location: 'Main Server Room Rack 2',
    status: 'ACTIVE',
    c_val: 4,
    i_val: 4,
    a_val: 4,
  },
  {
    id: 'da_samc_8',
    client_id: clientId,
    asset_code: 'AST-FW-008',
    asset_name: 'SAMA-Fortigate 100F',
    asset_type: 'IT Asset',
    asset_category: 'Firewall',
    asset_owner: 'IT Manager',
    classification: 'CONFIDENTIAL',
    location: 'Edge Network Rack',
    status: 'ACTIVE',
    c_val: 4,
    i_val: 4,
    a_val: 4,
  },
  {
    id: 'da_samc_9',
    client_id: clientId,
    asset_code: 'AST-PRN-009',
    asset_name: 'Brother MFC-L5755DW Printer,,DENTAL-RECEP-PRN-1',
    asset_type: 'IT Asset',
    asset_category: 'Other',
    asset_owner: 'IT Manager',
    classification: 'CONFIDENTIAL',
    location: 'Front Desk Reception A',
    status: 'ACTIVE',
    c_val: 4,
    i_val: 4,
    a_val: 4,
  },
  {
    id: 'da_samc_10',
    client_id: clientId,
    asset_code: 'AST-WS-010',
    asset_name: 'OptiPlex 3090',
    asset_type: 'IT Asset',
    asset_category: 'Desktop',
    asset_owner: 'IT Manager',
    classification: 'CONFIDENTIAL',
    location: 'Clinical Operatory Room B',
    status: 'ACTIVE',
    c_val: 4,
    i_val: 4,
    a_val: 4,
  }
];

export const DENTAL_RISKS_TEMPLATE = (clientId: string): RiskItem[] => [
  {
    id: 'dr_samc_1',
    client_id: clientId,
    risk_id: 'SAMC-RR-01',
    domain: 'Access Control',
    asset_name: 'PowerEdge R750xs',
    risk_title: 'Unauthorized Access incident affecting PowerEdge R750xs',
    threat: 'Unauthorized system access due to weak passwords, privilege misuse, or unauthorized logins.',
    vulnerability: 'Inadequate password complexity rules, lack of privilege audits, or unmonitored login attempts.',
    existing_controls: 'Standard Windows domain password requirements, basic user groups.',
    impact: 3,
    likelihood: 3,
    risk_rating: 36, // (AV: 4 * I: 3 * L: 3)
    risk_owner: 'IT Manager',
    status: 'CLOSED',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Implement a centralized Identity and Access Management (IAM) system, enforce strong password policies, and perform quarterly privilege reviews.',
    identification_date: '2023-12-23',
    target_closing_date: '2026-07-03',
    residual_likelihood: 2,
    residual_impact: 2,
    residual_risk_rating: 16, // (AV: 4 * RI: 2 * RL: 2)
    recurrence: 'Ongoing',
    review_date: '2026-09-29',
    c_val: 4,
    i_val: 4,
    a_val: 4,
    asset_value: 4
  },
  {
    id: 'dr_samc_2',
    client_id: clientId,
    risk_id: 'SAMC-RR-02',
    domain: 'Physical and Environmental Security',
    asset_name: 'Socomec',
    risk_title: 'Power Failure incident affecting R750xs',
    threat: 'Sudden power outages or voltage fluctuations damaging servers and patient care equipment.',
    vulnerability: 'Missing or unmaintained Uninterruptible Power Supplies (UPS), lack of emergency generator.',
    existing_controls: 'Local server room UPS (15-min battery capacity).',
    impact: 3,
    likelihood: 3,
    risk_rating: 36, // (AV: 4 * 3 * 3)
    risk_owner: 'IT Manager',
    status: 'CLOSED',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Install central automated diesel generators, replace legacy UPS batteries annually, and test the power transfer mechanism semi-annually.',
    identification_date: '2023-12-23',
    target_closing_date: '2026-07-03',
    residual_likelihood: 2,
    residual_impact: 2,
    residual_risk_rating: 16, // (AV: 4 * 2 * 2)
    recurrence: 'Ongoing',
    review_date: '2026-09-29',
    c_val: 4,
    i_val: 4,
    a_val: 4,
    asset_value: 4
  },
  {
    id: 'dr_samc_3',
    client_id: clientId,
    risk_id: 'SAMC-RR-03',
    domain: 'Physical and Environmental Security',
    asset_name: 'Precision 5820 Tower',
    risk_title: 'Human Error incident affecting Tower',
    threat: 'Operational errors including incorrect data entry, accidental deletion, or misconfigurations by staff.',
    vulnerability: 'Complex, non-standard user interfaces, lack of double-authorization for critical tasks, or poor training.',
    existing_controls: 'Basic training, read-only profiles for junior staff.',
    impact: 3,
    likelihood: 3,
    risk_rating: 36, // (AV: 4 * 3 * 3)
    risk_owner: 'Clinic Manager',
    status: 'CLOSED',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Introduce change control procedures, require dual-approval for destructive actions, and host interactive compliance workshops.',
    identification_date: '2023-12-23',
    target_closing_date: '2026-07-03',
    residual_likelihood: 2,
    residual_impact: 3,
    residual_risk_rating: 24, // (AV: 4 * 3 * 2)
    recurrence: 'Ongoing',
    review_date: '2026-09-29',
    c_val: 4,
    i_val: 4,
    a_val: 4,
    asset_value: 4
  },
  {
    id: 'dr_samc_4',
    client_id: clientId,
    risk_id: 'SAMC-RR-04',
    domain: 'Access Control',
    asset_name: 'AUTOCLAVE',
    risk_title: 'Medical Device Failure incident affecting AUTOCLAVE',
    threat: 'Failure or cyber-compromise of connected clinical or biomedical devices.',
    vulnerability: 'Legacy firmware, unsegmented medical networks, lack of medical device security standard reviews.',
    existing_controls: 'Isolated device networks, OEM default configurations.',
    impact: 3,
    likelihood: 3,
    risk_rating: 45, // (AV: 5 * 3 * 3)
    risk_owner: 'Clinic Manager',
    status: 'CLOSED',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Enforce strict network segmentation (VLAN) for all connected clinical devices, restrict device access, and configure continuous network telemetry.',
    identification_date: '2023-12-23',
    target_closing_date: '2026-07-03',
    residual_likelihood: 2,
    residual_impact: 3,
    residual_risk_rating: 30, // (AV: 5 * 3 * 2)
    recurrence: 'Ongoing',
    review_date: '2026-09-29',
    c_val: 5,
    i_val: 5,
    a_val: 5,
    asset_value: 5
  },
  {
    id: 'dr_samc_5',
    client_id: clientId,
    risk_id: 'SAMC-RR-05',
    domain: 'Access Control',
    asset_name: 'DENTAL CHAIR UNIT',
    risk_title: 'Medical Device Failure incident affecting DENTAL CHAIR UNIT',
    threat: 'Failure or cyber-compromise of connected clinical or biomedical devices.',
    vulnerability: 'Legacy firmware, unsegmented medical networks, lack of medical device security standard reviews.',
    existing_controls: 'Isolated device networks, OEM default configurations.',
    impact: 3,
    likelihood: 3,
    risk_rating: 45, // (AV: 5 * 3 * 3)
    risk_owner: 'Clinic Manager',
    status: 'CLOSED',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Enforce strict network segmentation (VLAN) for all connected clinical devices, restrict device access, and configure continuous network telemetry.',
    identification_date: '2023-12-23',
    target_closing_date: '2026-07-03',
    residual_likelihood: 2,
    residual_impact: 3,
    residual_risk_rating: 30, // (AV: 5 * 3 * 2)
    recurrence: 'Ongoing',
    review_date: '2026-09-29',
    c_val: 5,
    i_val: 5,
    a_val: 5,
    asset_value: 5
  },
  {
    id: 'dr_samc_6',
    client_id: clientId,
    risk_id: 'SAMC-RR-06',
    domain: 'Access Control',
    asset_name: 'ULTRASOUND',
    risk_title: 'Data Breach incident affecting ULTRASOUND',
    threat: 'Exposure, disclosure, or theft of sensitive patient data, EMR records, or personal information.',
    vulnerability: 'Unencrypted data storage, unauthorized copy/download permissions, or unencrypted data in transit.',
    existing_controls: 'Role-based access controls on EMR system, signed confidentiality agreements.',
    impact: 3,
    likelihood: 3,
    risk_rating: 36, // (AV: 4 * 3 * 3)
    risk_owner: 'Clinic Manager',
    status: 'CLOSED',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Enable full-disk encryption (AES-256), configure Data Loss Prevention (DLP) rules, and establish secure encrypted file-sharing channels.',
    identification_date: '2023-12-23',
    target_closing_date: '2026-07-03',
    residual_likelihood: 2,
    residual_impact: 3,
    residual_risk_rating: 24, // (AV: 4 * 3 * 2)
    recurrence: 'Ongoing',
    review_date: '2026-09-29',
    c_val: 4,
    i_val: 4,
    a_val: 4,
    asset_value: 4
  },
  {
    id: 'dr_samc_7',
    client_id: clientId,
    risk_id: 'SAMC-RR-07',
    domain: 'Access Control',
    asset_name: 'PowerEdge R750xs',
    risk_title: 'Physical Security incident affecting PowerEdge R750xs',
    threat: 'Theft, physical vandalism, or unauthorized access to corporate server rooms and clinics.',
    vulnerability: 'Unsecured server doors, blind spots in CCTV coverage, or missing visitor logs.',
    existing_controls: 'Standard locked door with key access, basic CCTV in main corridor.',
    impact: 3,
    likelihood: 3,
    risk_rating: 36, // (AV: 4 * 3 * 3)
    risk_owner: 'IT Manager',
    status: 'CLOSED',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Install biometric card scanners on all server rooms, expand CCTV coverage to cover all egress points, and mandate visitor badges.',
    identification_date: '2023-12-23',
    target_closing_date: '2026-07-03',
    residual_likelihood: 2,
    residual_impact: 3,
    residual_risk_rating: 24, // (AV: 4 * 3 * 2)
    recurrence: 'Ongoing',
    review_date: '2026-09-29',
    c_val: 4,
    i_val: 4,
    a_val: 4,
    asset_value: 4
  },
  {
    id: 'dr_samc_8',
    client_id: clientId,
    risk_id: 'SAMC-RR-08',
    domain: 'Access Control',
    asset_name: 'PowerEdge R750xs',
    risk_title: 'Malware Infection incident affecting PowerEdge R750xs',
    threat: 'System infections via viruses, spyware, or trojans disrupting operations.',
    vulnerability: 'Missing web filters, lack of local administrative privilege restriction.',
    existing_controls: 'Standard anti-virus tools.',
    impact: 3,
    likelihood: 3,
    risk_rating: 36, // (AV: 4 * 3 * 3)
    risk_owner: 'IT Manager',
    status: 'CLOSED',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Deploy Next-Generation Antivirus (NGAV), configure central DNS-based web content filtering, and restrict local admin rights.',
    identification_date: '2023-12-23',
    target_closing_date: '2026-07-03',
    residual_likelihood: 2,
    residual_impact: 3,
    residual_risk_rating: 24, // (AV: 4 * 3 * 2)
    recurrence: 'Ongoing',
    review_date: '2026-09-29',
    c_val: 4,
    i_val: 4,
    a_val: 4,
    asset_value: 4
  },
  {
    id: 'dr_samc_9',
    client_id: clientId,
    risk_id: 'SAMC-RR-09',
    domain: 'Access Control',
    asset_name: 'TS-832PX',
    risk_title: 'Backup Failure incident affecting TS-832PX',
    threat: 'Inability to restore systems due to corrupt backups, silent job failures, or insufficient NAS storage.',
    vulnerability: 'No automated restore testing, unmonitored backup failure notifications.',
    existing_controls: 'Manual check of backup logs periodically.',
    impact: 3,
    likelihood: 3,
    risk_rating: 36, // (AV: 4 * 3 * 3)
    risk_owner: 'IT Manager',
    status: 'OPEN',
    mitigation_status: 'Open',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Transition to automated, immutable cloud-based backups, set up real-time alerting for backup jobs, and conduct quarterly restore drills.',
    identification_date: '2023-12-23',
    target_closing_date: '2026-07-03',
    residual_likelihood: 2,
    residual_impact: 3,
    residual_risk_rating: 24, // (AV: 4 * 3 * 2)
    recurrence: 'Ongoing',
    review_date: '2026-09-29',
    c_val: 4,
    i_val: 4,
    a_val: 4,
    asset_value: 4
  },
  {
    id: 'dr_samc_10',
    client_id: clientId,
    risk_id: 'SAMC-RR-10',
    domain: 'Access Control',
    asset_name: 'TS-832PX',
    risk_title: 'Data Breach incident affecting TS-832PX',
    threat: 'Exposure, disclosure, or theft of sensitive patient data, records, or personal information.',
    vulnerability: 'Unencrypted data storage, unauthorized copy/download permissions, or unencrypted data in transit.',
    existing_controls: 'Role-based access controls on EMR system, signed confidentiality agreements.',
    impact: 3,
    likelihood: 3,
    risk_rating: 36, // (AV: 4 * 3 * 3)
    risk_owner: 'IT Manager',
    status: 'CLOSED',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Enable full-disk encryption (AES-256), configure Data Loss Prevention (DLP) rules, and establish secure encrypted file-sharing channels.',
    identification_date: '2023-12-23',
    target_closing_date: '2026-07-03',
    residual_likelihood: 2,
    residual_impact: 3,
    residual_risk_rating: 24, // (AV: 4 * 3 * 2)
    recurrence: 'Ongoing',
    review_date: '2026-09-29',
    c_val: 4,
    i_val: 4,
    a_val: 4,
    asset_value: 4
  },
  {
    id: 'dr_samc_11',
    client_id: clientId,
    risk_id: 'SAMC-RR-11',
    domain: 'Access Control',
    asset_name: 'SAMA-Fortigate 100F',
    risk_title: 'Cyber Attack incident affecting SAMA-Fortigate 100F',
    threat: 'Potential cyber attack compromising systems via malware, ransomware, phishing, or hacking.',
    vulnerability: 'Lack of advanced threat protection, missing security updates, or insufficient user training.',
    existing_controls: 'Basic firewall, corporate antivirus, periodic security alerts.',
    impact: 3,
    likelihood: 3,
    risk_rating: 36, // (AV: 4 * 3 * 3)
    risk_owner: 'IT Manager',
    status: 'CLOSED',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Deploy endpoint detection and response (EDR), enforce multi-factor authentication (MFA), and run monthly phishing simulations.',
    identification_date: '2023-12-23',
    target_closing_date: '2026-07-03',
    residual_likelihood: 2,
    residual_impact: 3,
    residual_risk_rating: 24, // (AV: 4 * 3 * 2)
    recurrence: 'Ongoing',
    review_date: '2026-09-29',
    c_val: 4,
    i_val: 4,
    a_val: 4,
    asset_value: 4
  },
  {
    id: 'dr_samc_12',
    client_id: clientId,
    risk_id: 'SAMC-RR-12',
    domain: 'Access Control',
    asset_name: 'Brother MFC-L5755DW Printer,,DENTAL-RECEP-PRN-1',
    risk_title: 'Compliance Risk incident affecting Brother MFC-L5755DW Printer,,DENTAL-RECEP-PRN-1',
    threat: 'Unauthorized access to network printers and non-compliance with regulatory security requirements such as DOH, ADHICS v2, and ISO 27001.',
    vulnerability: 'No internal audit program, outdated compliance documentation, or missing policy frameworks.',
    existing_controls: 'Annual compliance reviews, basic checklists.',
    impact: 3,
    likelihood: 3,
    risk_rating: 36, // (AV: 4 * 3 * 3)
    risk_owner: 'IT Manager',
    status: 'CLOSED',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Enforce secure print release policies, disable unused printer protocols, change default administrative credentials, and conduct bi-annual printer compliance audits.',
    identification_date: '2023-12-23',
    target_closing_date: '2026-07-03',
    residual_likelihood: 2,
    residual_impact: 2,
    residual_risk_rating: 16, // (AV: 4 * 2 * 2)
    recurrence: 'Ongoing',
    review_date: '2026-09-29',
    c_val: 4,
    i_val: 4,
    a_val: 4,
    asset_value: 4
  },
  {
    id: 'dr_samc_13',
    client_id: clientId,
    risk_id: 'SAMC-RR-13',
    domain: 'Access Control',
    asset_name: 'OptiPlex 3090',
    risk_title: 'Software Vulnerability incident affecting OptiPlex 3090',
    threat: 'Use of Windows 10 Pro systems may expose the organization to security threats if security updates, patches, and configurations are not properly maintained.',
    vulnerability: 'No centralized patch management system, obsolete third-party libraries.',
    existing_controls: 'Manual software updates conducted periodically by IT.',
    impact: 3,
    likelihood: 3,
    risk_rating: 36, // (AV: 4 * 3 * 3)
    risk_owner: 'IT Manager',
    status: 'TREATMENT_PLAN',
    mitigation_status: 'Treated',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Implement an automated central patch management system (e.g., WSUS), mandate vulnerability scanning, and sunset legacy systems.',
    identification_date: '2023-12-23',
    target_closing_date: '2026-07-03',
    residual_likelihood: 2,
    residual_impact: 2,
    residual_risk_rating: 16, // (AV: 4 * 2 * 2)
    recurrence: 'Ongoing',
    review_date: '2026-09-29',
    c_val: 4,
    i_val: 4,
    a_val: 4,
    asset_value: 4
  }
];
