/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Client, User, Policy, RiskItem, Asset, Incident, Audit, AuditFinding, CorrectiveAction, ComplianceForm, DocumentItem, Notification, AuditLog, EmailLog, SMTPSetting, Employee } from './types';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'c_akmc',
    client_code: 'AKMC',
    company_name: 'AL KHAJA MEDICAL CENTER',
    trade_license_no: 'TL-AD-88210',
    license_expiry: '2027-12-31',
    facility_type: 'Medical Center',
    address: 'Abu Dhabi, United Arab Emirates',
    city: 'Abu Dhabi',
    country: 'United Arab Emirates',
    email: 'info@alkhajamedicalcenter.ae',
    phone: '+971 2 6720048',
    website: 'https://alkhajamedicalcenter.ae',
    compliance_framework: 'DOH Abu Dhabi & MALAFFI & ADHICS v2',
    status: 'ACTIVE',
    created_at: '2023-01-01T08:00:00Z',
    updated_at: '2026-05-29T14:30:00Z',
    doc_version: '1.0',
    doc_ref: 'ZZP-IT-PE-05/2021',
    doc_classification: 'RESTRICTED',
    doc_issue_date: '01/03/2022',
    doc_approved_date: '30/06/2026',
    version_history: [
      { version: '1.0', date: '01/03/2022', author: 'Managing Director / IT Lead', changes: 'Initial document issue & approval under ISO 27001 & ADHICS v2 Framework' }
    ],
    doh_license_no: 'DOH-MC-4401',
    owner_name: 'DR TITTY MATHEW',
    owner_email: 'titty@alkhajamedicalcenter.ae',
    logo_placement: 'LEFT',
    facility_logo: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="%23059669" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><line x1="12" y1="8" x2="12" y2="16"/><line x1="8" y1="12" x2="16" y2="12"/></svg>',
    facility_stamp: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100"><circle cx="50" cy="50" r="40" fill="none" stroke="%23059669" stroke-width="4" stroke-dasharray="4"/><circle cx="50" cy="50" r="32" fill="none" stroke="%23059669" stroke-width="2"/><text x="50" y="42" font-family="sans-serif" font-size="8" font-weight="bold" fill="%23059669" text-anchor="middle">AL KHAJA MEDICAL</text><text x="50" y="55" font-family="sans-serif" font-size="12" font-weight="black" fill="%23059669" text-anchor="middle">APPROVED</text><text x="50" y="68" font-family="sans-serif" font-size="6" fill="%23059669" text-anchor="middle">DOH CONFORMITY</text></svg>',
    auth_representative: {
      name: 'DR TITTY MATHEW',
      email: 'titty@alkhajamedicalcenter.ae',
      phone: '+971 56 6437407'
    },
    clinic_manager: {
      name: 'Clinic Manager',
      email: 'manager@alkhajamedicalcenter.ae',
      phone: '+971 2 6720048'
    },
    medical_director: {
      name: 'DR TITTY MATHEW',
      email: 'info@alkhajamedicalcenter.ae',
      phone: '+971 2 6720048'
    },
    it_manager: {
      name: 'Aseef Sulaiman',
      email: 'info@smartpro.ae',
      phone: '+971 52 4846770'
    },
    hr_manager: {
      name: 'HR Manager',
      email: 'hr@alkhajamedicalcenter.ae',
      phone: '+971 2 6720048'
    },
    it_support: {
      team_name: 'Aseef Sulaiman',
      email: 'info@smartpro.ae',
      phone: '+971 52 4846770'
    },
    emr_support: {
      team_name: 'Beema Yoosaf',
      email: 'beema@safecaretec.com',
      phone: '+971 2 506 7300'
    }
  },
  {
    id: 'c0',
    client_code: 'SPRC',
    company_name: 'SmartPro Public Relations Consultancy & Cyber Risk Management Services',
    trade_license_no: 'TL-AD-10192',
    license_expiry: '2028-12-31',
    facility_type: 'Cyber Security & Compliance Consultancy',
    address: 'Al Mafraq, Abu Dhabi',
    city: 'Abu Dhabi',
    country: 'United Arab Emirates',
    email: 'info@smartpro.ae',
    phone: '0524846770',
    website: 'https://smartpro.ae',
    compliance_framework: 'DOH Abu Dhabi & MALAFFI & ISO 27001',
    status: 'ACTIVE',
    created_at: '2024-01-01T08:00:00Z',
    updated_at: '2026-05-29T14:30:00Z',
    doc_version: '1.0',
    doc_ref: 'ZZP-IT-PE-05/2021',
    doc_classification: 'RESTRICTED',
    doc_issue_date: '01/03/2022',
    doc_approved_date: '30/06/2026',
    version_history: [
      { version: '1.0', date: '01/03/2022', author: 'Managing Director / IT Lead', changes: 'Initial document issue & approval under ISO 27001 & ADHICS v2 Framework' }
    ],
    doh_license_no: 'DOH-CONS-9921',
    owner_name: 'Aseef Sulaiman',
    owner_email: 'info@smartpro.ae',
    logo_placement: 'LEFT',
    facility_logo: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="%230ea5e9" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><circle cx="12" cy="12" r="3"/></svg>',
    facility_stamp: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 160 160" width="160" height="160"><circle cx="80" cy="80" r="75" fill="none" stroke="%231d4ed8" stroke-width="2.5"/><circle cx="80" cy="80" r="69" fill="none" stroke="%231d4ed8" stroke-width="1.2" stroke-dasharray="3 1"/><circle cx="80" cy="80" r="50" fill="none" stroke="%231d4ed8" stroke-width="1.2"/><path id="curve-top" d="M 22 80 A 58 58 0 1 1 138 80" fill="none"/><text font-family="sans-serif" font-size="7.5" font-weight="900" fill="%231d4ed8" letter-spacing="1.2"><textPath href="%23curve-top" startOffset="50%" text-anchor="middle">SMARTPRO CONSULTANCY * سمارت برو للاستشارات</textPath></text><path id="curve-bottom" d="M 138 80 A 58 58 0 0 1 22 80" fill="none"/><text font-family="sans-serif" font-size="8" font-weight="900" fill="%231d4ed8" letter-spacing="1.5"><textPath href="%23curve-bottom" startOffset="50%" text-anchor="middle">* ABU DHABI - UAE • أبوظبي *</textPath></text><g transform="translate(64, 52) scale(1.35)"><path d="M12 2L4 5v6.09c0 5.05 3.41 9.76 8 10.91 4.59-1.15 8-5.86 8-10.91V5l-8-3z" fill="none" stroke="%231d4ed8" stroke-width="1.8" stroke-linejoin="round"/><path d="M9 11l2 2 4-4" fill="none" stroke="%231d4ed8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></g><text x="80" y="114" font-family="sans-serif" font-size="7" font-weight="900" fill="%231d4ed8" text-anchor="middle" letter-spacing="0.5">OFFICIAL SEAL</text><text x="80" y="123" font-family="sans-serif" font-size="6.5" font-weight="800" fill="%231d4ed8" text-anchor="middle" letter-spacing="0.5">APPROVED</text></svg>',
    auth_representative: {
      name: 'Aseef Sulaiman',
      email: 'info@smartpro.ae',
      phone: '0524846770'
    },
    clinic_manager: {
      name: 'Aseef Sulaiman',
      email: 'info@smartpro.ae',
      phone: '0524846770'
    }
  },
  {
    id: 'c4',
    client_code: 'ANP-04',
    company_name: 'AL NASR PHARMACY - LLC',
    trade_license_no: 'PF1045',
    license_expiry: '2026-12-31',
    facility_type: 'Pharmacy',
    address: 'Central District - Hai Al Murabbaa - Abu Dhabi',
    city: 'Abu Dhabi',
    country: 'United Arab Emirates',
    email: 'nasrpharmacy@gmail.com',
    phone: '0509680219',
    website: 'nasrpharmacy@gmail.com',
    compliance_framework: 'ISO 27001 & ADHICS v2',
    status: 'ACTIVE',
    created_at: '2023-05-12T08:00:00Z',
    updated_at: '2026-05-29T14:30:00Z',
    doc_version: '1.0',
    doc_ref: 'ZZP-IT-PE-05/2021',
    doc_classification: 'RESTRICTED',
    doc_issue_date: '01/03/2022',
    doc_approved_date: '30/06/2026',
    version_history: [
      { version: '1.0', date: '01/03/2022', author: 'Managing Director / IT Lead', changes: 'Initial document issue & approval under ISO 27001 & ADHICS v2 Framework' }
    ],
    doh_license_no: 'PF1045',
    owner_name: 'N/A',
    owner_email: 'nasrpharmacy@gmail.com',
    logo_placement: 'LEFT',
    facility_logo: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="%23dc2626" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><line x1="12" y1="8" x2="12" y2="16"/><line x1="8" y1="12" x2="16" y2="12"/></svg>',
    facility_stamp: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100"><circle cx="50" cy="50" r="40" fill="none" stroke="%23dc2626" stroke-width="4" stroke-dasharray="4"/><circle cx="50" cy="50" r="32" fill="none" stroke="%23dc2626" stroke-width="2"/><text x="50" y="42" font-family="sans-serif" font-size="8" font-weight="bold" fill="%23dc2626" text-anchor="middle">AL NASR PHARMACY</text><text x="50" y="55" font-family="sans-serif" font-size="12" font-weight="black" fill="%23dc2626" text-anchor="middle">OFFICIAL</text><text x="50" y="68" font-family="sans-serif" font-size="6" fill="%23dc2626" text-anchor="middle">ADHICS COMPLIANT</text></svg>',
    auth_representative: {
      name: 'Faizal',
      email: 'nasrpharma@emirated.net.ae',
      phone: '0509680219'
    },
    clinic_manager: {
      name: 'Aseef Sulaiman',
      email: 'info@smartpro.ae',
      phone: '0524846770'
    },
    medical_director: {
      name: 'Dr. Michael Roberts',
      email: 'medical.director@partner.ae',
      phone: '+971 50 123 4567'
    },
    it_manager: {
      name: 'aseef',
      email: 'info@smartpro.ae',
      phone: '0524846770'
    },
    hr_manager: {
      name: 'Sarah Jenkins',
      email: 'hr@partner.ae',
      phone: '+971 50 987 6543'
    },
    it_support: {
      team_name: 'Aseef',
      email: 'Tst@tesr.com',
      phone: '0556969783'
    },
    emr_support: {
      team_name: 'fdfsdf',
      email: 'dfsdf',
      phone: '05512345677'
    }
  },
  {
    id: 'c1',
    client_code: 'CCAD-01',
    company_name: 'Cleveland Clinic Abu Dhabi (CCAD)',
    trade_license_no: 'TL-AD-99812',
    license_expiry: '2027-02-15',
    facility_type: 'Multi-Specialty Hospital',
    address: 'Al Maryah Island',
    city: 'Abu Dhabi',
    country: 'United Arab Emirates',
    email: 'compliance@clevelandclinicabudhabi.ae',
    phone: '+971 2 659 0200',
    website: 'https://www.clevelandclinicabudhabi.ae',
    compliance_framework: 'DOH Abu Dhabi & MALAFFI & ISO 27001',
    status: 'ACTIVE',
    created_at: '2025-01-10T08:00:00Z',
    updated_at: '2026-05-12T14:30:00Z',
    doh_license_no: 'DOH-LH-77291',
    owner_name: 'Dr. Michael Roberts (CEO)',
    owner_email: 'm.roberts@clevelandclinic.ae',
    logo_placement: 'LEFT',
    facility_logo: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="%23059669" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><line x1="12" y1="8" x2="12" y2="16"/><line x1="8" y1="12" x2="16" y2="12"/></svg>',
    facility_stamp: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100"><circle cx="50" cy="50" r="40" fill="none" stroke="%23059669" stroke-width="4" stroke-dasharray="4"/><circle cx="50" cy="50" r="32" fill="none" stroke="%23059669" stroke-width="2"/><text x="50" y="42" font-family="sans-serif" font-size="8" font-weight="bold" fill="%23059669" text-anchor="middle">CCAD INTERNAL</text><text x="50" y="55" font-family="sans-serif" font-size="12" font-weight="black" fill="%23059669" text-anchor="middle">QMS SEAK</text><text x="50" y="68" font-family="sans-serif" font-size="6" fill="%23059669" text-anchor="middle">APPROVED OFFICE</text></svg>'
  },
  {
    id: 'c2',
    client_code: 'AZHD-02',
    company_name: 'Al Zahra Hospital Dubai',
    trade_license_no: 'TL-DXB-55310',
    license_expiry: '2026-09-30',
    facility_type: 'General Hospital',
    address: 'Sheikh Zayed Rd, Al Barsha 1',
    city: 'Dubai',
    country: 'United Arab Emirates',
    email: 'quality@alzahra.ae',
    phone: '+971 4 378 6666',
    website: 'https://alzahra.ae',
    compliance_framework: 'DHA & NABIDH & ISO 27001',
    status: 'ACTIVE',
    created_at: '2025-03-01T09:00:00Z',
    updated_at: '2026-04-18T11:15:00Z',
    doh_license_no: 'DHA-H-11094',
    owner_name: 'Garth Richardson (MD)',
    owner_email: 'garth.richardson@alzahra.ae',
    logo_placement: 'RIGHT',
    facility_logo: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="%230284c7" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 12h-4l-3 9L9 3l-3 9H2"/></svg>',
    facility_stamp: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100"><circle cx="50" cy="50" r="40" fill="none" stroke="%230284c7" stroke-width="4" stroke-dasharray="4"/><circle cx="50" cy="50" r="32" fill="none" stroke="%230284c7" stroke-width="2"/><text x="50" y="42" font-family="sans-serif" font-size="8" font-weight="bold" fill="%230284c7" text-anchor="middle">AZHD REGULATORY</text><text x="50" y="55" font-family="sans-serif" font-size="12" font-weight="black" fill="%230284c7" text-anchor="middle">VERIFIED</text><text x="50" y="68" font-family="sans-serif" font-size="6" fill="%230284c7" text-anchor="middle">DHA COMPLIANT</text></svg>'
  },
  {
    id: 'c3',
    client_code: 'MC-03',
    company_name: 'Al Noor Medical Centre Al Ain',
    trade_license_no: 'TL-AA-44122',
    license_expiry: '2026-07-20',
    facility_type: 'Day Care Clinic',
    address: 'Khalifa Street',
    city: 'Al Ain',
    country: 'United Arab Emirates',
    email: 'info@alnoormedical.ae',
    phone: '+971 3 766 8888',
    website: 'https://alnoor.ae',
    compliance_framework: 'DOH Abu Dhabi & MALAFFI',
    status: 'ACTIVE',
    created_at: '2025-06-15T10:00:00Z',
    updated_at: '2026-01-20T16:45:00Z',
    doh_license_no: 'DOH-LH-88294',
    owner_name: 'Dr. Salem Al-Mansouri (Owner)',
    owner_email: 'salem@alnoormedical.ae',
    logo_placement: 'FULL',
    facility_logo: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="%234f46e5" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 8l-4 4h8z"/></svg>',
    facility_stamp: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100"><circle cx="50" cy="50" r="40" fill="none" stroke="%234f46e5" stroke-width="4" stroke-dasharray="4"/><circle cx="50" cy="50" r="32" fill="none" stroke="%234f46e5" stroke-width="2"/><text x="50" y="42" font-family="sans-serif" font-size="8" font-weight="bold" fill="%234f46e5" text-anchor="middle">MALAFFI OFFICE</text><text x="50" y="55" font-family="sans-serif" font-size="12" font-weight="black" fill="%234f46e5" text-anchor="middle">AUTHORIZED</text><text x="50" y="68" font-family="sans-serif" font-size="6" fill="%234f46e5" text-anchor="middle">DOH CONFORMITY</text></svg>'
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'u_aseef',
    role: 'SUPER_ADMIN',
    full_name: 'Aseef Sulaiman (Master DB Admin)',
    email: 'aseef',
    tenant_id: 'TNT-MASTER-DB-LOCAL',
    mobile: '+971 52 4846770',
    is_active: true,
    last_login: '2026-08-02T05:00:00Z',
    created_at: '2025-01-01T08:00:00Z'
  },
  {
    id: 'u1',
    role: 'SUPER_ADMIN',
    full_name: 'Sarah Jenkins',
    email: 'sarah.jenkins@smarthub.io',
    tenant_id: 'TNT-GLOBAL-01',
    mobile: '+971 50 123 4567',
    is_active: true,
    last_login: '2026-06-25T11:30:00-07:00',
    created_at: '2025-01-01T08:00:00Z'
  },
  {
    id: 'u2',
    role: 'CONSULTANT',
    full_name: 'Tareq Al Mansoori',
    email: 'tareq.m@smarthub.io',
    tenant_id: 'TNT-CONSULT-02',
    mobile: '+971 52 888 1234',
    is_active: true,
    last_login: '2026-06-25T09:15:00-07:00',
    created_at: '2025-01-15T09:00:00Z'
  },
  {
    id: 'u3',
    client_id: 'c1',
    role: 'CLIENT_ADMIN',
    full_name: 'Dr. Johnathan Carter',
    email: 'j.carter@clevelandclinicabudhabi.ae',
    tenant_id: 'TNT-CCAD-8821',
    mobile: '+971 54 333 4455',
    is_active: true,
    last_login: '2026-06-24T15:45:00-07:00',
    created_at: '2025-01-12T10:00:00Z'
  },
  {
    id: 'u4',
    client_id: 'c2',
    role: 'AUDITOR',
    full_name: 'Elena Rostova',
    email: 'e.rostova@external-auditor.com',
    tenant_id: 'TNT-AUDIT-4491',
    mobile: '+971 55 999 0011',
    is_active: true,
    last_login: '2026-06-22T10:00:00-07:00',
    created_at: '2025-04-10T11:00:00Z'
  },
  {
    id: 'u5',
    client_id: 'c3',
    role: 'READ_ONLY',
    full_name: 'Fatima Al Kaabi',
    email: 'f.alkaabi@alnoormedical.ae',
    tenant_id: 'TNT-ALNOOR-3301',
    mobile: '+971 50 444 8899',
    is_active: true,
    last_login: '2026-06-25T11:10:00-07:00',
    created_at: '2025-06-20T12:00:00Z'
  }
];

export const INITIAL_POLICIES: Policy[] = [
  {
    id: 'p1',
    client_id: 'c1',
    policy_no: 'POL-ISM-001',
    policy_name: 'Information Security Management Policy',
    version: '2.1',
    review_date: '2026-08-15',
    status: 'APPROVED',
    category: 'Information Security',
    document_path: 'documents/c1/POL-ISM-001_v2.1.pdf',
    created_at: '2025-01-15T09:00:00Z'
  },
  {
    id: 'p2',
    client_id: 'c1',
    policy_no: 'POL-DOH-MALAFFI',
    policy_name: 'MALAFFI Connection and Patient Privacy Standards',
    version: '1.2',
    review_date: '2026-07-30',
    status: 'APPROVED',
    category: 'Patient Data Privacy',
    document_path: 'documents/c1/POL-DOH-MALAFFI_v1.2.pdf',
    created_at: '2025-02-10T10:00:00Z'
  },
  {
    id: 'p3',
    client_id: 'c1',
    policy_no: 'POL-AM-005',
    policy_name: 'Biomedical Equipment PPM Compliance Standard',
    version: '1.0',
    review_date: '2026-06-30',
    status: 'UNDER_REVIEW',
    category: 'Asset Management',
    document_path: 'documents/c1/POL-AM-005_v1.0.pdf',
    created_at: '2025-06-20T11:00:00Z'
  },
  {
    id: 'p4',
    client_id: 'c2',
    policy_no: 'POL-NABIDH-02',
    policy_name: 'DHA NABIDH EHR Integration & Security Standard',
    version: '2.0',
    review_date: '2026-09-01',
    status: 'APPROVED',
    category: 'EHR Security',
    document_path: 'documents/c2/POL-NABIDH-02_v2.0.pdf',
    created_at: '2025-03-10T09:30:00Z'
  },
  {
    id: 'p5',
    client_id: 'c2',
    policy_no: 'POL-BC-09',
    policy_name: 'Business Continuity and Disaster Recovery Plan',
    version: '1.1',
    review_date: '2026-05-10',
    status: 'EXPIRED',
    category: 'Business Continuity',
    document_path: 'documents/c2/POL-BC-09_v1.1.pdf',
    created_at: '2025-04-15T14:00:00Z'
  }
];

export const INITIAL_RISK_ITEMS: RiskItem[] = [
  {
    id: 'r_nasr_1',
    client_id: 'c4',
    risk_id: 'RSK-RR-001',
    domain: 'Access Control',
    asset_name: 'Firewall',
    risk_title: 'Weak passwords',
    threat: 'Weak passwords - Susceptibility to brute-force or credential stuffing due to simple or guessable credentials.',
    vulnerability: 'Susceptibility to brute-force or credential stuffing',
    existing_controls: 'Basic password length requirement',
    impact: 4,
    likelihood: 4,
    risk_rating: 16,
    risk_owner: 'IT Manager',
    status: 'OPEN',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Enforce complex password policies and implement MFA.',
    identification_date: '2023-05-18',
    target_closing_date: '2026-05-30',
    residual_likelihood: 2,
    residual_impact: 3,
    residual_risk_rating: 6,
    recurrence: 'Ongoing',
    review_date: '2026-09-29'
  },
  {
    id: 'r_nasr_2',
    client_id: 'c4',
    risk_id: 'RSK-RR-002',
    domain: 'Communications and Operations Management',
    asset_name: 'Firewall',
    risk_title: 'Ransomware attack',
    threat: 'Ransomware attack - Malicious software that encrypts data and demands payment for decryption.',
    vulnerability: 'Lack of offline backups and advanced endpoint protection',
    existing_controls: 'Antivirus, weekly backups',
    impact: 5,
    likelihood: 4,
    risk_rating: 20,
    risk_owner: 'IT Manager',
    status: 'OPEN',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Maintain immutable backups, and conduct security awareness training.',
    identification_date: '2023-05-18',
    target_closing_date: '2026-05-30',
    residual_likelihood: 2,
    residual_impact: 4,
    residual_risk_rating: 8,
    recurrence: 'Ongoing',
    review_date: '2026-09-29'
  },
  {
    id: 'r_nasr_3',
    client_id: 'c4',
    risk_id: 'RSK-RR-003',
    domain: 'Communications and Operations Management',
    asset_name: 'Firewall',
    risk_title: 'Misconfiguration',
    threat: 'System flaws or service exposure allowing malicious entry or data leak due to improper server or network setup.',
    vulnerability: 'Default system configs and open administrative interfaces',
    existing_controls: 'Standard initial setups, manual server updates',
    impact: 4,
    likelihood: 3,
    risk_rating: 12,
    risk_owner: 'IT Manager',
    status: 'OPEN',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Establish secure configuration baselines, change all default configs, and use configuration management tools.',
    identification_date: '2023-05-18',
    target_closing_date: '2026-05-30',
    residual_likelihood: 1,
    residual_impact: 3,
    residual_risk_rating: 3,
    recurrence: 'Ongoing',
    review_date: '2026-09-29'
  },
  {
    id: 'r_nasr_4',
    client_id: 'c4',
    risk_id: 'RSK-RR-004',
    domain: 'Compliance',
    asset_name: 'Firewall',
    risk_title: 'Weak policies',
    threat: 'Inconsistent compliance with modern data protection regulations, leading to audit failures and fines.',
    vulnerability: 'Using generic, outdated risk management template files',
    existing_controls: 'Standard onboarding papers',
    impact: 3,
    likelihood: 3,
    risk_rating: 9,
    risk_owner: 'IT Manager',
    status: 'OPEN',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Review and update policies annually to align with ADHICS, ISO 27001',
    identification_date: '2023-05-18',
    target_closing_date: '2026-05-30',
    residual_likelihood: 1,
    residual_impact: 2,
    residual_risk_rating: 2,
    recurrence: 'Ongoing',
    review_date: '2026-09-29'
  },
  {
    id: 'r_nasr_5',
    client_id: 'c4',
    risk_id: 'RSK-RR-005',
    domain: 'Third-Party Security',
    asset_name: 'Firewall',
    risk_title: 'Third-party risks',
    threat: 'Data breach at an external cloud service provider exposing patient record histories.',
    vulnerability: 'Absence of vendor security audits or service agreements',
    existing_controls: 'General contract reviews',
    impact: 4,
    likelihood: 3,
    risk_rating: 12,
    risk_owner: 'IT Manager',
    status: 'OPEN',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Implement strong third-party assessment procedures and establish strict SLA agreements with data-protection mandates.',
    identification_date: '2023-05-18',
    target_closing_date: '2026-05-30',
    residual_likelihood: 1,
    residual_impact: 3,
    residual_risk_rating: 3,
    recurrence: 'Ongoing',
    review_date: '2026-09-29'
  },
  {
    id: 'r_nasr_6',
    client_id: 'c4',
    risk_id: 'RSK-RR-006',
    domain: 'Communications and Operations Management',
    asset_name: 'Desktop',
    risk_title: 'Unpatched OS / vulnerabilities',
    threat: 'Exploitation of known software weaknesses due to missing security updates.',
    vulnerability: 'Delayed patch management cycle',
    existing_controls: 'Manual patching process',
    impact: 4,
    likelihood: 4,
    risk_rating: 16,
    risk_owner: 'IT Manager',
    status: 'OPEN',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Automate patch management and perform monthly checkup.',
    identification_date: '2023-05-18',
    target_closing_date: '2026-09-30',
    residual_likelihood: 2,
    residual_impact: 3,
    residual_risk_rating: 6,
    recurrence: 'Ongoing',
    review_date: '2026-09-29'
  },
  {
    id: 'r_nasr_7',
    client_id: 'c4',
    risk_id: 'RSK-RR-007',
    domain: 'Physical and Environmental Security',
    asset_name: 'Desktop',
    risk_title: 'Unauthorized USB usage',
    threat: 'Physical data theft or malware introduction via unmanaged mass storage devices.',
    vulnerability: 'Physical data theft or malware introduction',
    existing_controls: 'Physical security',
    impact: 4,
    likelihood: 3,
    risk_rating: 12,
    risk_owner: 'IT Manager',
    status: 'OPEN',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Disable USB ports via local policy or implement endpoint port control.',
    identification_date: '2023-05-18',
    target_closing_date: '2026-05-30',
    residual_likelihood: 1,
    residual_impact: 3,
    residual_risk_rating: 3,
    recurrence: 'Ongoing',
    review_date: '2026-09-29'
  },
  {
    id: 'r_nasr_8',
    client_id: 'c4',
    risk_id: 'RSK-RR-008',
    domain: 'Access Control',
    asset_name: 'Desktop',
    risk_title: 'Weak passwords',
    threat: 'Susceptibility to brute-force or credential stuffing due to simple or guessable credentials.',
    vulnerability: 'Susceptibility to brute-force or credential stuffing',
    existing_controls: 'Basic password length requirement',
    impact: 4,
    likelihood: 4,
    risk_rating: 16,
    risk_owner: 'IT Manager',
    status: 'OPEN',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Enforce complex password policies',
    identification_date: '2023-05-18',
    target_closing_date: '2026-05-30',
    residual_likelihood: 2,
    residual_impact: 3,
    residual_risk_rating: 6,
    recurrence: 'Ongoing',
    review_date: '2026-09-29'
  },
  {
    id: 'r_nasr_9',
    client_id: 'c4',
    risk_id: 'RSK-RR-009',
    domain: 'Information Systems Acquisition, Development, and Maintenance',
    asset_name: 'Desktop',
    risk_title: 'Outdated software',
    threat: 'Using legacy, insecure versions of charting utilities that are vulnerable to well-known exploits.',
    vulnerability: 'Lack of software inventory tracking or lifecycle updates',
    existing_controls: 'Ad-hoc manual upgrades',
    impact: 4,
    likelihood: 4,
    risk_rating: 16,
    risk_owner: 'IT Manager',
    status: 'OPEN',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Establish a software update pipeline and deprecate end-of-life applications.',
    identification_date: '2023-05-18',
    target_closing_date: '2026-05-30',
    residual_likelihood: 2,
    residual_impact: 3,
    residual_risk_rating: 6,
    recurrence: 'Ongoing',
    review_date: '2026-09-29'
  },
  {
    id: 'r_nasr_10',
    client_id: 'c4',
    risk_id: 'RSK-RR-010',
    domain: 'Compliance',
    asset_name: 'Desktop',
    risk_title: 'Weak policies',
    threat: 'Inconsistent compliance with modern data protection regulations, leading to audit failures and fines.',
    vulnerability: 'Using generic, outdated risk management template files',
    existing_controls: 'Standard onboarding papers',
    impact: 3,
    likelihood: 3,
    risk_rating: 9,
    risk_owner: 'IT Manager',
    status: 'OPEN',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Review and update policies annually to align with ADHICS, ISO 27001.',
    identification_date: '2023-05-18',
    target_closing_date: '2026-05-30',
    residual_likelihood: 1,
    residual_impact: 2,
    residual_risk_rating: 2,
    recurrence: 'Ongoing',
    review_date: '2026-09-29'
  },
  {
    id: 'r_nasr_11',
    client_id: 'c4',
    risk_id: 'RSK-RR-011',
    domain: 'Communications and Operations Management',
    asset_name: 'Desktop',
    risk_title: 'Antivirus (Expire, Trail, Not installed)',
    threat: 'Malicious software infecting clinical workstations due to outdated signature databases.',
    vulnerability: 'Unlicensed or disabled antivirus clients on clinical PCs',
    existing_controls: 'Local Windows Defender setups',
    impact: 4,
    likelihood: 4,
    risk_rating: 16,
    risk_owner: 'IT Manager',
    status: 'OPEN',
    mitigation_status: 'In progress',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Install and configure auto-updates with real-time health checks.',
    identification_date: '2023-05-18',
    target_closing_date: '2026-08-31',
    residual_likelihood: 2,
    residual_impact: 3,
    residual_risk_rating: 6,
    recurrence: 'Ongoing',
    review_date: '2026-09-29'
  },
  {
    id: 'r_nasr_12',
    client_id: 'c4',
    risk_id: 'RSK-RR-012',
    domain: 'Communications and Operations Management',
    asset_name: 'Desktop',
    risk_title: 'Device OS (outdated, Trail, Crack, not activate)',
    threat: 'Ransomware infection and system instability due to a lack of security patches on unlicensed operating systems.',
    vulnerability: 'Using cracked operating systems or outdated software builds',
    existing_controls: 'Ad-hoc manual updates',
    impact: 5,
    likelihood: 4,
    risk_rating: 20,
    risk_owner: 'IT Manager',
    status: 'OPEN',
    mitigation_status: 'In progress',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Upgrade all systems to fully licensed Windows 11 pro and plan to updates via WSUS.',
    identification_date: '2023-05-18',
    target_closing_date: '2026-09-30',
    residual_likelihood: 2,
    residual_impact: 4,
    residual_risk_rating: 8,
    recurrence: 'Ongoing',
    review_date: '2026-09-29'
  },
  {
    id: 'r_nasr_13',
    client_id: 'c4',
    risk_id: 'RSK-RR-013',
    domain: 'Compliance',
    asset_name: 'Printer',
    risk_title: 'Weak policies',
    threat: 'Inconsistent compliance with modern data protection regulations, leading to audit failures and fines.',
    vulnerability: 'Using generic, outdated risk management template files',
    existing_controls: 'Standard onboarding papers',
    impact: 3,
    likelihood: 3,
    risk_rating: 9,
    risk_owner: 'IT Manager',
    status: 'OPEN',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Review and update policies annually to align with ADHICS, ISO 27001',
    identification_date: '2023-05-18',
    target_closing_date: '2026-06-05',
    residual_likelihood: 1,
    residual_impact: 2,
    residual_risk_rating: 2,
    recurrence: 'Ongoing',
    review_date: '2026-09-29'
  },
  {
    id: 'r_nasr_14',
    client_id: 'c4',
    risk_id: 'RSK-RR-014',
    domain: 'Access Control',
    asset_name: 'CCTV',
    risk_title: 'Shared passwords',
    threat: 'Complete loss of audit trails, making it impossible to attribute unauthorized scheduling modifications to a specific individual.',
    vulnerability: 'Multiple employees using one generic login to access booking computer systems',
    existing_controls: 'Staff group memory of passcodes',
    impact: 3,
    likelihood: 4,
    risk_rating: 12,
    risk_owner: 'IT Manager',
    status: 'OPEN',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Enforce individual user logins for all personnel and backed by MFA.',
    identification_date: '2023-05-18',
    target_closing_date: '2026-06-05',
    residual_likelihood: 2,
    residual_impact: 2,
    residual_risk_rating: 4,
    recurrence: 'Ongoing',
    review_date: '2026-09-29'
  },
  {
    id: 'r_nasr_15',
    client_id: 'c4',
    risk_id: 'RSK-RR-015',
    domain: 'Communications and Operations Management',
    asset_name: 'WiFI Access Point',
    risk_title: 'Guest network misuse',
    threat: 'Tech-savvy guests running local network scans and launching cyber-attacks against EMR services.',
    vulnerability: 'Lack of network segregation between clinic systems and patient Wi-Fi',
    existing_controls: 'Encrypted staff Wi-Fi',
    impact: 4,
    likelihood: 3,
    risk_rating: 12,
    risk_owner: 'IT Manager',
    status: 'OPEN',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Configure separate logical VLANs to isolate guests from internal nodes, and enforce a landing portal with terms of use.',
    identification_date: '2023-05-18',
    target_closing_date: '2026-05-30',
    residual_likelihood: 1,
    residual_impact: 3,
    residual_risk_rating: 3,
    recurrence: 'Ongoing',
    review_date: '2026-09-29'
  },
  {
    id: 'r_nasr_16',
    client_id: 'c4',
    risk_id: 'RSK-RR-016',
    domain: 'Data Privacy and Protection',
    asset_name: 'HSA Software',
    risk_title: 'Unencrypted devices',
    threat: 'Physical theft of portable devices leading to absolute clinical data exposure because the hard drive lacks encryption-at-rest.',
    vulnerability: 'Disabled BitLocker or FileVault encryption',
    existing_controls: 'Device logins, BIOS security',
    impact: 5,
    likelihood: 4,
    risk_rating: 20,
    risk_owner: 'IT Manager',
    status: 'OPEN',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Mandate Full Disk Encryption, GPO, secure recovery keys centrally.',
    identification_date: '2023-05-18',
    target_closing_date: '2026-05-30',
    residual_likelihood: 2,
    residual_impact: 4,
    residual_risk_rating: 8,
    recurrence: 'Ongoing',
    review_date: '2026-09-29'
  },
  {
    id: 'r_nasr_17',
    client_id: 'c4',
    risk_id: 'RSK-RR-017',
    domain: 'Access Control',
    asset_name: 'HSA Software',
    risk_title: 'Weak passwords',
    threat: 'Susceptibility to brute-force or credential stuffing due to simple or guessable credentials.',
    vulnerability: 'Susceptibility to brute-force or credential stuffing',
    existing_controls: 'Basic password length requirement',
    impact: 4,
    likelihood: 4,
    risk_rating: 16,
    risk_owner: 'IT Manager',
    status: 'OPEN',
    mitigation_status: 'Closed',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Enforce complex password policies and implement MFA.',
    identification_date: '2023-05-18',
    target_closing_date: '2026-06-05',
    residual_likelihood: 2,
    residual_impact: 3,
    residual_risk_rating: 6,
    recurrence: 'Ongoing',
    review_date: '2026-09-29'
  },
  {
    id: 'r_nasr_18',
    client_id: 'c4',
    risk_id: 'RSK-RR-018',
    domain: 'Communications and Operations Management',
    asset_name: 'Windows 11 Pro',
    risk_title: 'Unpatched OS / vulnerabilities',
    threat: 'Exploitation of known software weaknesses due to missing security updates.',
    vulnerability: 'Delayed patch management cycle',
    existing_controls: 'Manual patching process',
    impact: 4,
    likelihood: 4,
    risk_rating: 16,
    risk_owner: 'IT Manager',
    status: 'OPEN',
    mitigation_status: 'In progress',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Automate patch management and perform weekly vulnerability scans.',
    identification_date: '2023-05-18',
    target_closing_date: '2026-09-30',
    residual_likelihood: 2,
    residual_impact: 3,
    residual_risk_rating: 6,
    recurrence: 'Ongoing',
    review_date: '2026-09-29'
  },
  {
    id: 'r_nasr_19',
    client_id: 'c4',
    risk_id: 'RSK-RR-019',
    domain: 'Communications and Operations Management',
    asset_name: 'Antivirus Application',
    risk_title: 'Device OS (outdated, Trail, Crack, not activate)',
    threat: 'Ransomware infection and system instability due to a lack of security patches on unlicensed operating systems.',
    vulnerability: 'Using cracked operating systems or outdated software builds',
    existing_controls: 'Ad-hoc manual updates',
    impact: 5,
    likelihood: 4,
    risk_rating: 20,
    risk_owner: 'IT Manager',
    status: 'OPEN',
    mitigation_status: 'In progress',
    record_status: 'Active',
    treatment_option: 'Reduction',
    treatment_plan: 'Upgrade all systems to fully licensed Windows 11 pro and automate updates via WSUS.',
    identification_date: '2023-05-18',
    target_closing_date: '2026-07-31',
    residual_likelihood: 2,
    residual_impact: 4,
    residual_risk_rating: 8,
    recurrence: 'Ongoing',
    review_date: '2026-09-29'
  },
  {
    id: 'r1',
    client_id: 'c1',
    risk_id: 'RSK-SEC-01',
    risk_title: 'Unauthenticated EMR Database Access Risk',
    asset_name: 'Epic EMR Database Server',
    threat: 'Unauthorized database logins resulting in HIPAA/MALAFFI breaches',
    vulnerability: 'Weak administrative accounts password standards and lacks enforced multi-factor authentication (MFA)',
    impact: 5,
    likelihood: 3,
    risk_rating: 15,
    existing_controls: 'Firewall restricted network segment, active server directory logs monitoring.',
    treatment_plan: 'Enforce strong, rotating passwords and implement MFA via integration with Entra ID.',
    risk_owner: 'Dr. Johnathan Carter',
    review_date: '2026-09-10',
    status: 'TREATMENT_PLAN',
    created_at: '2025-01-20T08:00:00Z'
  },
  {
    id: 'r2',
    client_id: 'c1',
    risk_id: 'RSK-BIO-04',
    risk_title: 'Biomedical Ventilator Software Failure',
    asset_name: 'ICU Ventilator Suite (Hamilton G5)',
    threat: 'Software glitch halts ventilation assistance, endangering patient life',
    vulnerability: 'Outdated firmware version 3.2.0 lacks safety patching, and manual safety testing overdue',
    impact: 5,
    likelihood: 2,
    risk_rating: 10,
    existing_controls: 'Audible emergency hardware alarm system on physical ventilators.',
    treatment_plan: 'Perform emergency upgrade to firmware v3.3.1 and schedules urgent physical safety inspections.',
    risk_owner: 'Aymen Al Awadi (Biomedical Eng)',
    review_date: '2026-07-15',
    status: 'OPEN',
    created_at: '2025-04-05T09:00:00Z'
  },
  {
    id: 'r3',
    client_id: 'c2',
    risk_id: 'RSK-NAB-09',
    risk_title: 'Unencrypted Transmission of NABIDH Sync Payloads',
    asset_name: 'NABIDH Sync Gateway API',
    threat: 'Eavesdropping on healthcare network payloads, compromising clinical records',
    vulnerability: 'Gateway transmits clinical data using legacy TLS 1.0 protocols and weak cipher suites',
    impact: 4,
    likelihood: 4,
    risk_rating: 16,
    existing_controls: 'Data payload is tokenized; patient identifying names are hashed.',
    treatment_plan: 'Upgrade APIs to force TLS 1.3 protocol and restrict permitted cipher lists.',
    risk_owner: 'Elena Rostova',
    review_date: '2026-07-05',
    status: 'TREATMENT_PLAN',
    created_at: '2025-05-12T10:00:00Z'
  },
  {
    id: 'r4',
    client_id: 'c3',
    risk_id: 'RSK-PHY-03',
    risk_title: 'Unrestricted Access to Server Room',
    asset_name: 'Main Comms Rack & Servers',
    threat: 'Malicious modification of server hardware or accidental disconnects',
    vulnerability: 'Server room door lock is broken, allowing any visitor or employee access',
    impact: 4,
    likelihood: 3,
    risk_rating: 12,
    existing_controls: 'CCTV camera coverage in the hallway facing the entrance.',
    treatment_plan: 'Repair electronic swipe key lock and install access card logging system.',
    risk_owner: 'Fatima Al Kaabi',
    review_date: '2026-08-01',
    status: 'OPEN',
    created_at: '2025-08-15T11:00:00Z'
  }
];

export const INITIAL_ASSETS: Asset[] = [
  {
    id: 'a_nasr_1',
    client_id: 'c4',
    asset_code: 'AST-FW-001',
    asset_name: 'Firewall',
    asset_type: 'IT Asset',
    asset_category: 'Firewall',
    description: 'Bespoke firewall security gateway protecting pharmacy server networks.',
    manufacturer: 'Fortinet',
    model: 'FortiGate 60F',
    serial_number: 'FG60F-NASR',
    asset_owner: 'Aseef Sulaiman',
    classification: 'RESTRICTED',
    location: 'Pharmacy Comms Closet',
    status: 'ACTIVE',
    c_val: 5,
    i_val: 5,
    a_val: 5
  },
  {
    id: 'a_nasr_2',
    client_id: 'c4',
    asset_code: 'AST-WS-002',
    asset_name: 'Desktop',
    asset_type: 'IT Asset',
    asset_category: 'Desktop',
    description: 'Workstations used for order processing and billing systems.',
    manufacturer: 'HP',
    model: 'ProDesk 400',
    serial_number: 'HPPD-NASR',
    asset_owner: 'Aseef Sulaiman',
    classification: 'CONFIDENTIAL',
    location: 'Billing & Front Desks',
    status: 'ACTIVE',
    c_val: 3,
    i_val: 3,
    a_val: 3
  },
  {
    id: 'a_nasr_3',
    client_id: 'c4',
    asset_code: 'AST-PRN-003',
    asset_name: 'Printer',
    asset_type: 'IT Asset',
    asset_category: 'Printer',
    description: 'Receipt and prescription barcode printer.',
    manufacturer: 'Zebra',
    model: 'ZD220',
    serial_number: 'ZBPR-NASR',
    asset_owner: 'Aseef Sulaiman',
    classification: 'CONFIDENTIAL',
    location: 'Dispensing Counters',
    status: 'ACTIVE',
    c_val: 3,
    i_val: 3,
    a_val: 3
  },
  {
    id: 'a_nasr_4',
    client_id: 'c4',
    asset_code: 'AST-CCT-004',
    asset_name: 'CCTV',
    asset_type: 'IT Asset',
    asset_category: 'CCTV',
    description: 'Bespoke surveillance system monitoring clinical storage areas.',
    manufacturer: 'Hikvision',
    model: 'DS-2CD',
    serial_number: 'HKCV-NASR',
    asset_owner: 'Aseef Sulaiman',
    classification: 'CONFIDENTIAL',
    location: 'Pharmacy Perimeter & Medicine Vault',
    status: 'ACTIVE',
    c_val: 4,
    i_val: 5,
    a_val: 4
  },
  {
    id: 'a_nasr_5',
    client_id: 'c4',
    asset_code: 'AST-WIFI-005',
    asset_name: 'WiFI Access Point',
    asset_type: 'IT Asset',
    asset_category: 'Other',
    description: 'Wireless access point providing guest and staff network nodes.',
    manufacturer: 'Ubiquiti',
    model: 'UniFi U6 Lite',
    serial_number: 'UBAP-NASR',
    asset_owner: 'Aseef Sulaiman',
    classification: 'CONFIDENTIAL',
    location: 'Waiting Lobby Ceiling',
    status: 'ACTIVE',
    c_val: 2,
    i_val: 2,
    a_val: 3
  },
  {
    id: 'a_nasr_6',
    client_id: 'c4',
    asset_code: 'AST-AV-006',
    asset_name: 'Antivirus Application',
    asset_type: 'Software Asset',
    asset_category: 'License',
    description: 'Endpoint detection and response (EDR) software client.',
    manufacturer: 'Bitdefender',
    model: 'GravityZone',
    serial_number: 'LIC-AV-NASR',
    asset_owner: 'Aseef Sulaiman',
    classification: 'CONFIDENTIAL',
    location: 'All Workstations',
    status: 'ACTIVE',
    c_val: 3,
    i_val: 3,
    a_val: 3
  },
  {
    id: 'a_nasr_7',
    client_id: 'c4',
    asset_code: 'AST-WOS-007',
    asset_name: 'Windows 11 Pro',
    asset_type: 'Software Asset',
    asset_category: 'Windows OS',
    description: 'Operating systems running on clinical devices.',
    manufacturer: 'Microsoft',
    model: 'Windows 11 Professional',
    serial_number: 'LIC-OS-NASR',
    asset_owner: 'Aseef Sulaiman',
    classification: 'CONFIDENTIAL',
    location: 'All Workstations',
    status: 'ACTIVE',
    c_val: 3,
    i_val: 4,
    a_val: 4
  },
  {
    id: 'a_nasr_8',
    client_id: 'c4',
    asset_code: 'AST-EMR-008',
    asset_name: 'HSA Software',
    asset_type: 'Software Asset',
    asset_category: 'EMR Software',
    description: 'Electronic medical prescription and records syncing engine.',
    manufacturer: 'HSA MENA',
    model: 'RxSuite v2.1',
    serial_number: 'LIC-EMR-NASR',
    asset_owner: 'Malik Imran Hussain',
    classification: 'CONFIDENTIAL',
    location: 'Local Workstations & Cloud Sync',
    status: 'ACTIVE',
    c_val: 5,
    i_val: 5,
    a_val: 5
  },
  {
    id: 'a_nasr_9',
    client_id: 'c4',
    asset_code: 'AST-NAS-009',
    asset_name: 'NAS Backup Storage',
    asset_type: 'IT Asset',
    asset_category: 'NAS',
    description: 'Network attached storage vault holding offline data backups and server logs.',
    manufacturer: 'Synology',
    model: 'DiskStation DS923+',
    serial_number: 'SYNAS-NASR',
    asset_owner: 'Aseef Sulaiman',
    classification: 'CONFIDENTIAL',
    location: 'Pharmacy Comms Closet',
    status: 'ACTIVE',
    c_val: 5,
    i_val: 5,
    a_val: 4
  },
  {
    id: 'a_nasr_10',
    client_id: 'c4',
    asset_code: 'AST-PHN-010',
    asset_name: 'Reception IP-Phone',
    asset_type: 'IT Asset',
    asset_category: 'IP-Phone',
    description: 'Clinical telephone network handset for patient appointments.',
    manufacturer: 'Cisco',
    model: 'IP Phone 8841',
    serial_number: 'CSCPH-NASR',
    asset_owner: 'Aseef Sulaiman',
    classification: 'CONFIDENTIAL',
    location: 'Front Reception Desk',
    status: 'ACTIVE',
    c_val: 3,
    i_val: 3,
    a_val: 4
  },
  {
    id: 'a_nasr_11',
    client_id: 'c4',
    asset_code: 'AST-UPS-011',
    asset_name: 'Server Rack UPS',
    asset_type: 'IT Asset',
    asset_category: 'UPS',
    description: 'Uninterruptible power supply supporting servers and network devices during power cuts.',
    manufacturer: 'APC',
    model: 'Smart-UPS 1500VA',
    serial_number: 'APCUPS-NASR',
    asset_owner: 'Aseef Sulaiman',
    classification: 'CONFIDENTIAL',
    location: 'Pharmacy Comms Closet',
    status: 'ACTIVE',
    c_val: 1,
    i_val: 3,
    a_val: 5
  },
  {
    id: 'a_nasr_12',
    client_id: 'c4',
    asset_code: 'AST-EML-012',
    asset_name: 'Outlook Corporate Email',
    asset_type: 'Software Asset',
    asset_category: 'Email Software',
    description: 'Corporate communications platform hosting patient receipts and medical workflows.',
    manufacturer: 'Microsoft',
    model: 'Microsoft 365 Exchange',
    serial_number: 'LIC-EML-NASR',
    asset_owner: 'Aseef Sulaiman',
    classification: 'CONFIDENTIAL',
    location: 'Cloud Platform',
    status: 'ACTIVE',
    c_val: 5,
    i_val: 4,
    a_val: 4
  },
  {
    id: 'a1',
    client_id: 'c1',
    asset_code: 'AST-IT-101',
    asset_name: 'Epic EMR Central Database Server',
    asset_type: 'IT Asset',
    asset_category: 'Server',
    description: 'Central transactional database engine hosting patient electronic medical records.',
    manufacturer: 'Hewlett Packard Enterprise',
    model: 'ProLiant DL380 Gen10',
    serial_number: 'SGH812CCAD',
    asset_owner: 'Dr. Johnathan Carter',
    classification: 'RESTRICTED',
    location: 'DC Server Room - Row B Rack 3',
    purchase_date: '2023-05-10',
    warranty_expiry: '2026-05-10',
    eol_date: '2028-12-31',
    eos_date: '2029-12-31',
    ppm_date: '2026-05-15',
    ppm_due_date: '2026-11-15',
    status: 'ACTIVE',
    remarks: 'Critical database server. Do not restart during patient active hours.'
  },
  {
    id: 'a2',
    client_id: 'c1',
    asset_code: 'AST-BIO-004',
    asset_name: 'Hamilton-G5 High-End Ventilator Suite',
    asset_type: 'Biomedical Asset',
    asset_category: 'Medical Device',
    description: 'Critical care ventilator for adult, pediatric, and neonatal patients in ICU.',
    manufacturer: 'Hamilton Medical',
    model: 'G5 Suite',
    serial_number: 'VENT-H90812-CCAD',
    asset_owner: 'Aymen Al Awadi (Biomedical Eng)',
    classification: 'CONFIDENTIAL',
    location: 'ICU Department - Room 104',
    purchase_date: '2022-08-20',
    warranty_expiry: '2025-08-20',
    eol_date: '2029-01-01',
    eos_date: '2030-01-01',
    ppm_date: '2026-03-10',
    ppm_due_date: '2026-09-10',
    status: 'ACTIVE',
    remarks: 'Annual PPM schedule highly critical due to ventilation parameters calibration.'
  },
  {
    id: 'a3',
    client_id: 'c1',
    asset_code: 'AST-SW-055',
    asset_name: 'MALAFFI HIE Sync Connector Client',
    asset_type: 'Software Asset',
    asset_category: 'EMR Software',
    description: 'API engine middleware syncing patient files to Abu Dhabi Malaffi Health Information Exchange.',
    manufacturer: 'Malaffi HIE Client Suite',
    model: 'v4.2 Enterprise',
    serial_number: 'LIC-MAL-883921-CCAD',
    asset_owner: 'IT Systems Admin Team',
    classification: 'CONFIDENTIAL',
    location: 'Virtual Host - CC-VM-MALAFFI',
    purchase_date: '2024-01-15',
    warranty_expiry: '2027-01-15',
    eol_date: '2027-12-31',
    eos_date: '2028-12-31',
    ppm_date: '2026-06-01',
    ppm_due_date: '2026-12-01',
    status: 'ACTIVE',
    remarks: 'Required for active operational license compliance with DOH.'
  },
  {
    id: 'a4',
    client_id: 'c2',
    asset_code: 'AST-BIO-309',
    asset_name: 'GE Voluson E10 Ultrasound Machine',
    asset_type: 'Biomedical Asset',
    asset_category: 'Ultrasound',
    description: '4D ultrasound system for obstetrics, gynecology, and clinical imaging.',
    manufacturer: 'GE HealthCare',
    model: 'Voluson E10',
    serial_number: 'US-GE-99812-AZ',
    asset_owner: 'Radiology Operations',
    classification: 'CONFIDENTIAL',
    location: 'Radiology Lab - Room 3',
    purchase_date: '2021-12-05',
    warranty_expiry: '2024-12-05',
    eol_date: '2027-12-05',
    eos_date: '2028-12-05',
    ppm_date: '2026-01-15',
    ppm_due_date: '2026-07-15',
    status: 'ACTIVE',
    remarks: 'Transducer probe replacement due in upcoming PPM audit.'
  },
  {
    id: 'a5',
    client_id: 'c2',
    asset_code: 'AST-SEC-402',
    asset_name: 'Fortinet Enterprise Core Firewall',
    asset_type: 'IT Asset',
    asset_category: 'Firewall',
    description: 'Core firewall managing clinical vs guest network segmentation policies.',
    manufacturer: 'Fortinet',
    model: 'FortiGate 200F',
    serial_number: 'FG200F-AZHD',
    asset_owner: 'Elena Rostova',
    classification: 'RESTRICTED',
    location: 'Main Telecom Rack Room',
    purchase_date: '2024-05-15',
    warranty_expiry: '2027-05-15',
    eol_date: '2030-05-15',
    eos_date: '2031-05-15',
    ppm_date: '2025-11-20',
    ppm_due_date: '2026-05-20',
    status: 'ACTIVE',
    remarks: 'PPM overdue! Security firmware upgrade required immediately to fix SSL-VPN bug.'
  }
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'i1',
    client_id: 'c1',
    incident_no: 'INC-2026-001',
    incident_title: 'MALAFFI Health Sync Feed Disconnected',
    description: 'The MALAFFI sync endpoint failed to exchange clinical summaries for 14 hours. Detected via log monitor alerts.',
    severity: 'CRITICAL',
    root_cause: 'API credential certificates expired on the middleware proxy. Notification email fell into the spam folder.',
    corrective_action: 'Automate certification check scripts and change credentials alerts to Slack and WhatsApp integrations.',
    incident_owner: 'Dr. Johnathan Carter',
    reported_date: '2026-05-10',
    closed_date: '2026-05-11',
    closure_status: 'CLOSED',
    created_at: '2026-05-10T14:00:00Z'
  },
  {
    id: 'i2',
    client_id: 'c1',
    incident_no: 'INC-2026-002',
    incident_title: 'Unauthorized Access Attempt to Patient Care Records',
    description: 'An external IP address from Ukraine attempted login into CCAD portal with an administrator username 150 times.',
    severity: 'HIGH',
    root_cause: 'Attacker targeted known administrative username with password spray attack.',
    corrective_action: 'Lockout account after 5 failed logins, and disable access to standard admin login portal from public internet IPs without VPN tunnel.',
    incident_owner: 'Sarah Jenkins',
    reported_date: '2026-06-18',
    closure_status: 'INVESTIGATING',
    created_at: '2026-06-18T10:00:00Z'
  }
];

export const INITIAL_AUDITS: Audit[] = [
  {
    id: 'au1',
    client_id: 'c1',
    audit_number: 'AUD-CCAD-2026-01',
    audit_type: 'REGULATORY',
    audit_scope: 'DOH Abu Dhabi Patient Health Records Privacy Compliance and MALAFFI sync audit.',
    auditor_name: 'DOH Audit Inspector Board',
    audit_date: '2026-05-15',
    report_path: 'reports/c1/AUD_CCAD_2026_01.pdf',
    status: 'COMPLETED',
    created_at: '2026-05-01T10:00:00Z'
  },
  {
    id: 'au2',
    client_id: 'c2',
    audit_number: 'AUD-AZ-2026-03',
    audit_type: 'INTERNAL',
    audit_scope: 'Information Security Risk and Asset Protection Management audit under ISO 27001.',
    auditor_name: 'Elena Rostova',
    audit_date: '2026-06-20',
    status: 'IN_PROGRESS',
    created_at: '2026-06-01T11:00:00Z'
  },
  {
    id: 'au3',
    client_id: 'c3',
    audit_number: 'AUD-MC-2026-01',
    audit_type: 'EXTERNAL',
    audit_scope: 'Annual clinical standards and medical device calibration verification.',
    auditor_name: 'TUV Middle East Inspectorate',
    audit_date: '2026-07-15',
    status: 'PLANNED',
    created_at: '2026-06-15T12:00:00Z'
  }
];

export const INITIAL_FINDINGS: AuditFinding[] = [
  {
    id: 'f1',
    audit_id: 'au1',
    finding_no: 'FND-CCAD-01',
    finding_description: 'Audit logs for EMR record access are not centralized or backed up offsite. Critical lack of forensic readiness.',
    finding_type: 'NC_MINOR',
    severity: 'MEDIUM',
    recommendation: 'Establish an automated Rsync or Splunk agent job to push all security and audit trails to a secure cold-storage bucket daily.',
    status: 'CLOSED'
  },
  {
    id: 'f2',
    audit_id: 'au1',
    finding_no: 'FND-CCAD-02',
    finding_description: 'Unencrypted patient PII data transmitted via legacy internal email gateway without TLS enforcement.',
    finding_type: 'NC_MAJOR',
    severity: 'CRITICAL',
    recommendation: 'Enforce strict TLS 1.3 encryption on outbound mail flow and deploy Data Loss Prevention (DLP) rules.',
    status: 'OPEN'
  },
  {
    id: 'f3',
    audit_id: 'au1',
    finding_no: 'FND-CCAD-03',
    finding_description: 'Privileged IT Admin accounts missing enforced Multi-Factor Authentication (MFA) on internal VPN endpoint.',
    finding_type: 'NC_MAJOR',
    severity: 'CRITICAL',
    recommendation: 'Mandate TOTP/FIDO2 hardware token MFA for all administrative VPN sessions immediately.',
    status: 'RESOLVING'
  },
  {
    id: 'f4',
    audit_id: 'au1',
    finding_no: 'FND-CCAD-04',
    finding_description: 'Server room physical access logs lack quarterly reconciliation against HR termination list.',
    finding_type: 'NC_MINOR',
    severity: 'HIGH',
    recommendation: 'Automate physical access badge revocation upon HR status change in Active Directory.',
    status: 'OPEN'
  },
  {
    id: 'f5',
    audit_id: 'au1',
    finding_no: 'FND-CCAD-05',
    finding_description: 'Disaster Recovery Plan simulation test overdue by 45 days past scheduled annual review.',
    finding_type: 'NC_MINOR',
    severity: 'HIGH',
    recommendation: 'Conduct simulated tabletop disaster recovery failover drill and document lessons learned.',
    status: 'RESOLVING'
  },
  {
    id: 'f6',
    audit_id: 'au1',
    finding_no: 'FND-CCAD-06',
    finding_description: 'Minor formatting inconsistencies in vendor NDA agreement attachment templates.',
    finding_type: 'OFI',
    severity: 'LOW',
    recommendation: 'Update master document index templates to standardized ISO 27001 version 2.1 formatting.',
    status: 'CLOSED'
  },
  {
    id: 'f7',
    audit_id: 'au2',
    finding_no: 'FND-AZ-01',
    finding_description: 'Multiple biomedical devices (ultrasound machine, ventilators) lack PPM active labels and physical maintenance logs are disorganized.',
    finding_type: 'NC_MAJOR',
    severity: 'HIGH',
    recommendation: 'Re-inventory all active biomedical items, issue distinct QR asset tags, and deploy centralized maintenance tracking dashboards.',
    status: 'OPEN'
  },
  {
    id: 'f8',
    audit_id: 'au2',
    finding_no: 'FND-AZ-02',
    finding_description: 'Firewall rules configuration lacks annual documented review signatures.',
    finding_type: 'OFI',
    severity: 'LOW',
    recommendation: 'Add a mandatory annual policy task to verify firewall permissions and obtain CSO electronic signature approval.',
    status: 'RESOLVING'
  },
  {
    id: 'f9',
    audit_id: 'au2',
    finding_no: 'FND-AZ-03',
    finding_description: 'Unrestricted USB mass storage access enabled on workstation endpoints in billing department.',
    finding_type: 'NC_MAJOR',
    severity: 'CRITICAL',
    recommendation: 'Apply Group Policy Objects (GPO) to disable USB mass storage devices across all non-whitelisted clinical PCs.',
    status: 'OPEN'
  },
  {
    id: 'f10',
    audit_id: 'au3',
    finding_no: 'FND-MC-01',
    finding_description: 'Clinical laboratory diagnostic server running operating system past End-Of-Life (EOL).',
    finding_type: 'NC_MAJOR',
    severity: 'CRITICAL',
    recommendation: 'Upgrade host OS to supported LTS release and isolate legacy hardware on dedicated VLAN.',
    status: 'OPEN'
  },
  {
    id: 'f11',
    audit_id: 'au3',
    finding_no: 'FND-MC-02',
    finding_description: 'Staff security awareness training completion rate at 62%, below 90% target threshold.',
    finding_type: 'NC_MINOR',
    severity: 'MEDIUM',
    recommendation: 'Send automated reminder notifications to staff with incomplete training modules and mandate completion within 14 days.',
    status: 'RESOLVING'
  }
];

export const INITIAL_CORRECTIVE_ACTIONS: CorrectiveAction[] = [
  {
    id: 'ca1',
    client_id: 'c1',
    source_type: 'AUDIT_FINDING',
    source_reference: 'FND-CCAD-01',
    finding: 'Audit logs for EMR record access are not centralized or backed up offsite.',
    root_cause: 'IT infrastructure setup lacked automated storage workflows and dedicated cloud repositories.',
    action_plan: 'Configure automatic nightly log dumps, compress logs using Gzip, and stream payloads to Azure Storage Container.',
    responsible_person: 'Johnathan Carter (Client Admin)',
    target_date: '2026-06-30',
    completion_date: '2026-06-23',
    status: 'COMPLETED',
    created_at: '2026-05-18T10:00:00Z'
  },
  {
    id: 'ca2',
    client_id: 'c2',
    source_type: 'AUDIT_FINDING',
    source_reference: 'FND-AZ-01',
    finding: 'Biomedical devices lack physical PPM status stickers and safety calibration records.',
    root_cause: 'Calibration partner failed to print decals upon completion and quality officer lacked follow-up checklist.',
    action_plan: 'Recalibrate machinery, tag physical assets with custom weather-resistant stickers containing next-maintenance due dates, and update asset profiles inside compliance app.',
    responsible_person: 'Elena Rostova (Compliance Officer)',
    target_date: '2026-07-20',
    status: 'IN_PROGRESS',
    created_at: '2026-06-21T11:00:00Z'
  },
  {
    id: 'ca3',
    client_id: 'c1',
    source_type: 'INCIDENT',
    source_reference: 'INC-2026-001',
    finding: 'MALAFFI api feed was offline for 14 hours due to expired SSL client certificate.',
    root_cause: 'Certificate renewals are processed manually without email tracking or expiration calendars.',
    action_plan: 'Implement automated Let\'s Encrypt SSL renewing script, configure Google Calendar and app alerts for expiration 30 days ahead.',
    responsible_person: 'Dr. Johnathan Carter',
    target_date: '2026-05-25',
    completion_date: '2026-05-12',
    status: 'COMPLETED',
    created_at: '2026-05-11T09:00:00Z'
  }
];

export const INITIAL_FORMS: ComplianceForm[] = [
  {
    id: 'fm1',
    client_id: 'c1',
    doc_ref: 'FORM-ONB-NDA-001',
    form_name: 'Employee Confidentiality & Non-Disclosure Agreement (NDA)',
    form_type: 'Confidentiality/NDA Form',
    category: 'Onboarding',
    issue_date: '2024-01-15',
    expiry_date: '2027-01-15',
    review_date: '2027-01-15',
    version: 'v1.0',
    classification: 'CONFIDENTIAL',
    status: 'ACTIVE',
    prepared_by: 'HR & Legal Compliance Team',
    approved_by: 'Medical Director',
    description: 'Legally binding confidentiality and health data privacy agreement for newly onboarded clinical and administrative personnel in compliance with UAE Data Protection Law & DOH ADHICS.',
    total_submissions: 18
  },
  {
    id: 'fm2',
    client_id: 'c1',
    doc_ref: 'FORM-ONB-ORT-002',
    form_name: 'ORIENTATION CHECKLIST & Safety Protocol',
    form_type: 'Orientation Form',
    category: 'Onboarding',
    issue_date: '2024-02-01',
    expiry_date: '2027-02-01',
    review_date: '2027-02-01',
    version: 'v1.1',
    classification: 'RESTRICTED',
    status: 'ACTIVE',
    prepared_by: 'HR & Training Coordinator',
    approved_by: 'Clinic Manager',
    description: 'Structured onboarding orientation checklist covering facility tour, fire emergency exits, EMR & MALAFFI connection rules, biomedical device operation, and patient rights.',
    total_submissions: 24
  },
  {
    id: 'fm-inc-001',
    client_id: 'c1',
    doc_ref: 'FORM-INC-LOG-001',
    form_name: 'INCIDENT MANAGEMENT FORM',
    form_type: 'Incident Management Form',
    category: 'Incident Response',
    issue_date: '2024-02-15',
    expiry_date: '2027-02-15',
    review_date: '2027-02-15',
    version: 'v1.0',
    classification: 'RESTRICTED',
    status: 'ACTIVE',
    prepared_by: 'CISO / Incident Response Team',
    approved_by: 'Risk Review Committee',
    description: 'Official reporting and investigation log for healthcare cybersecurity incidents, EHR outages, and unauthorized patient data access attempts.',
    total_submissions: 12
  },
  {
    id: 'fm3',
    client_id: 'c1',
    doc_ref: 'FORM-IT-USR-003',
    form_name: 'IT User Account Creation & Access Rights Provisioning Request',
    form_type: 'User Creation Form',
    category: 'IT Security',
    issue_date: '2024-03-10',
    expiry_date: '2027-03-10',
    review_date: '2027-03-10',
    version: 'v2.0',
    classification: 'RESTRICTED',
    status: 'ACTIVE',
    prepared_by: 'IT Systems Admin',
    approved_by: 'IT Manager / CISO',
    description: 'Requisition form for issuing user credentials, official email, EMR/MALAFFI access levels, domain privileges, and multi-factor authentication setup for new staff.',
    total_submissions: 32
  },
  {
    id: 'fm4',
    client_id: 'c1',
    doc_ref: 'FORM-HR-VER-004',
    form_name: 'Pre-Employment Credential & Background Verification Record',
    form_type: 'Employee Verification Form',
    category: 'HR Compliance',
    issue_date: '2024-01-20',
    expiry_date: '2027-01-20',
    review_date: '2027-01-20',
    version: 'v1.0',
    classification: 'CONFIDENTIAL',
    status: 'ACTIVE',
    prepared_by: 'HR Compliance Officer',
    approved_by: 'HR Manager',
    description: 'Verification record attesting validity of healthcare professional licenses (DOH/DHA), university degrees, DataFlow primary source verification, and police clearance certificates.',
    total_submissions: 15
  },
  {
    id: 'fm5',
    client_id: 'c1',
    doc_ref: 'FORM-HR-REF-005',
    form_name: 'Staff Talent Acquisition & Employee Referral Form',
    form_type: 'Employee Referral Form',
    category: 'HR Compliance',
    issue_date: '2024-04-05',
    expiry_date: '2027-04-05',
    review_date: '2027-04-05',
    version: 'v1.0',
    classification: 'INTERNAL',
    status: 'ACTIVE',
    prepared_by: 'Recruitment Specialist',
    approved_by: 'HR Manager',
    description: 'Internal referral form for existing employees nominating qualified clinical or administrative candidates for open healthcare positions.',
    total_submissions: 9
  },
  {
    id: 'fm6',
    client_id: 'c1',
    doc_ref: 'FORM-OFF-CLR-006',
    form_name: 'Staff Exit Clearance & Asset Handover Sign-Off Form',
    form_type: 'Staff Clearance Form',
    category: 'Offboarding',
    issue_date: '2024-02-15',
    expiry_date: '2027-02-15',
    review_date: '2027-02-15',
    version: 'v1.2',
    classification: 'STRICTLY CONFIDENTIAL',
    status: 'ACTIVE',
    prepared_by: 'HR & IT Offboarding Desk',
    approved_by: 'Managing Director / Clinic Manager',
    description: 'Offboarding checklist confirming IT asset return (laptops/tokens), EMR/MALAFFI credential revocation, security access card hand-back, and final settlement release sign-off.',
    total_submissions: 11
  },
  {
    id: 'fm7',
    client_id: 'c1',
    doc_ref: 'FORM-IT-CRF-007',
    form_name: 'IT Systems & Infrastructure Change Request Form (CRF)',
    form_type: 'Change Request Form',
    category: 'Change Control',
    issue_date: '2024-01-10',
    expiry_date: '2027-01-10',
    review_date: '2027-01-10',
    version: 'v1.3',
    classification: 'RESTRICTED',
    status: 'ACTIVE',
    prepared_by: 'Senior IT Engineer',
    approved_by: 'IT Advisory Advisory Board (CAB)',
    description: 'Formal change management request for deploying system updates, server patches, network reconfigurations, software upgrades, or database schema changes.',
    total_submissions: 27
  }
];

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc1',
    client_id: 'c1',
    document_name: 'CCAD_ISO_27001_Certification_2025.pdf',
    document_type: 'PDF',
    version: '1.0',
    storage_path: 'repository/c1/cert_2025.pdf',
    approval_status: 'APPROVED',
    expiry_date: '2028-02-28',
    uploaded_by: 'u3',
    uploaded_by_name: 'Dr. Johnathan Carter',
    uploaded_at: '2025-02-15T09:00:00Z'
  },
  {
    id: 'doc2',
    client_id: 'c1',
    document_name: 'Biomedical_Calibration_Matrix_2026.xlsx',
    document_type: 'XLSX',
    version: '2.3',
    storage_path: 'repository/c1/calibration_matrix.xlsx',
    approval_status: 'APPROVED',
    expiry_date: '2026-12-31',
    uploaded_by: 'u3',
    uploaded_by_name: 'Dr. Johnathan Carter',
    uploaded_at: '2026-01-10T11:00:00Z'
  },
  {
    id: 'doc3',
    client_id: 'c2',
    document_name: 'DHA_NABIDH_Security_Compliance_Framework.docx',
    document_type: 'DOCX',
    version: '1.0',
    storage_path: 'repository/c2/nabidh_framework.docx',
    approval_status: 'PENDING_APPROVAL',
    uploaded_by: 'u4',
    uploaded_by_name: 'Elena Rostova',
    uploaded_at: '2026-06-20T15:30:00Z'
  },
  {
    id: 'doc-draft-reg2026-c1',
    client_id: 'c1',
    document_name: 'Official_Instrument_REG-2026_Draft.docx',
    document_code: 'REG-2026',
    document_type: 'DOCX',
    version: '0.1',
    storage_path: 'repository/c1/Official_Instrument_REG-2026_Draft.docx',
    approval_status: 'DRAFT',
    expiry_date: '2027-12-31',
    uploaded_by: 'u1',
    uploaded_by_name: 'Sarah Jenkins (Consultant)',
    uploaded_at: '2026-07-24T03:00:00Z',
    department: 'Quality & Governance',
    doc_type_category: 'Record',
    classification: 'Confidential',
    title: 'Official Instrument - Governance & Regulatory Standard',
    content: 'This Official Instrument defines the governance, physical security, risk management, and regulatory compliance protocols for the facility under ISO 27001 and ADHICS standards. All operational units must adhere to the policies set forth herein.',
    letterhead_mode: false
  },
  {
    id: 'doc-draft-reg2026-c2',
    client_id: 'c2',
    document_name: 'Official_Instrument_REG-2026_Draft.docx',
    document_code: 'REG-2026',
    document_type: 'DOCX',
    version: '0.1',
    storage_path: 'repository/c2/Official_Instrument_REG-2026_Draft.docx',
    approval_status: 'DRAFT',
    expiry_date: '2027-12-31',
    uploaded_by: 'u1',
    uploaded_by_name: 'Sarah Jenkins (Consultant)',
    uploaded_at: '2026-07-24T03:00:00Z',
    department: 'Quality & Governance',
    doc_type_category: 'Record',
    classification: 'Confidential',
    title: 'Official Instrument - Governance & Regulatory Standard',
    content: 'This Official Instrument defines the governance, physical security, risk management, and regulatory compliance protocols for the facility under ISO 27001 and ADHICS standards. All operational units must adhere to the policies set forth herein.',
    letterhead_mode: false
  }
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    client_id: 'c1',
    user_id: 'u1',
    title: 'Urgent: Policy Review Due Soon',
    message: 'The Information Security Management Policy (POL-ISM-001) review date is 2026-08-15. Ensure drafts are complete.',
    notification_type: 'POLICY_REVIEW',
    is_read: false,
    created_at: '2026-06-24T08:00:00Z'
  },
  {
    id: 'n2',
    client_id: 'c1',
    user_id: 'u3',
    title: 'Biomedical Asset PPM Schedule Notice',
    message: 'Hamilton-G5 High-End Ventilator Suite (AST-BIO-004) PPM calibration is due on 2026-09-10.',
    notification_type: 'ASSET_PPM',
    is_read: false,
    created_at: '2026-06-25T07:30:00Z'
  },
  {
    id: 'n3',
    client_id: 'c2',
    user_id: 'u1',
    title: 'Critical Overdue Asset PPM Alert',
    message: 'Fortinet Enterprise Core Firewall (AST-SEC-402) PPM schedule is OVERDUE since 2026-05-20. Firmware contains CVE vulnerability.',
    notification_type: 'ASSET_PPM',
    is_read: false,
    created_at: '2026-06-25T09:00:00Z'
  },
  {
    id: 'n4',
    client_id: 'c1',
    user_id: 'u1',
    title: 'Risk treatment plan overdue',
    message: 'Risk plan for EMR database (RSK-SEC-01) must be acknowledged by Dr. Johnathan Carter.',
    notification_type: 'RISK_REVIEW',
    is_read: true,
    created_at: '2026-06-20T10:00:00Z'
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'l1',
    client_id: 'c1',
    user_id: 'u3',
    user_name: 'Dr. Johnathan Carter',
    action: 'COMPLETED_CORRECTIVE_ACTION',
    module_name: 'Corrective Actions',
    record_id: 'ca1',
    new_value: { status: 'COMPLETED', completion_date: '2026-06-23' },
    ip_address: '192.168.10.45',
    created_at: '2026-06-23T16:00:00Z'
  },
  {
    id: 'l2',
    client_id: 'c1',
    user_id: 'u1',
    user_name: 'Sarah Jenkins',
    action: 'CREATE_POLICY',
    module_name: 'Policy Management',
    record_id: 'p3',
    new_value: { policy_name: 'Biomedical Equipment PPM Compliance Standard' },
    ip_address: '94.200.15.82',
    created_at: '2026-06-20T11:00:00Z'
  }
];

export const INITIAL_EMAIL_LOGS: EmailLog[] = [
  {
    id: 'e1',
    recipient_email: 'j.carter@clevelandclinicabudhabi.ae',
    subject: 'PPM Maintenance Due Reminder: AST-BIO-004',
    email_type: 'Asset PPM Reminder',
    status: 'SENT',
    sent_at: '2026-06-25T07:30:00Z'
  },
  {
    id: 'e2',
    recipient_email: 'e.rostova@external-auditor.com',
    subject: 'ISO 27001 Internal Audit Notification - AUD-AZ-2026-03',
    email_type: 'Audit Plan Notification',
    status: 'SENT',
    sent_at: '2026-06-01T11:05:00Z'
  }
];

export const DEFAULT_SMTP: SMTPSetting = {
  server: 'smtp.office365.com',
  port: 587,
  username: 'compliance.hub@smarthub.io',
  password: 'CompliancePass123!',
  sender_email: 'no-reply@smarthub.io',
  tls: true,
  ssl: false,
  provider: 'Office 365',
  sandbox_mode: false
};

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp1',
    client_id: 'c1',
    employee_id: 'EMP-CCAD-101',
    employee_name: 'Sarah Jenkins',
    position: 'Compliance Specialist',
    department: 'Quality Department',
    joining_date: '2023-01-15',
    current_status: 'Active'
  },
  {
    id: 'emp2',
    client_id: 'c1',
    employee_id: 'EMP-CCAD-102',
    employee_name: 'Dr. Johnathan Carter',
    position: 'Chief Medical Officer',
    department: 'Medical Operations',
    joining_date: '2021-06-01',
    current_status: 'Active'
  },
  {
    id: 'emp3',
    client_id: 'c1',
    employee_id: 'EMP-CCAD-103',
    employee_name: 'Fatima Al Mansoori',
    position: 'Information Security Officer',
    department: 'IT & Security',
    joining_date: '2024-03-10',
    current_status: 'Active'
  },
  {
    id: 'emp4',
    client_id: 'c1',
    employee_id: 'EMP-CCAD-104',
    employee_name: 'Mark Fletcher',
    position: 'Biomedical Technician',
    department: 'Facilities & Biomedical',
    joining_date: '2022-11-01',
    last_working_date: '2026-05-15',
    current_status: 'Resigned'
  },
  {
    id: 'emp5',
    client_id: 'c1',
    employee_id: 'EMP-CCAD-105',
    employee_name: 'Layla Al Hashimi',
    position: 'Junior Auditor',
    department: 'Quality Department',
    joining_date: '2025-02-15',
    current_status: 'Vacation'
  },
  {
    id: 'emp6',
    client_id: 'c2',
    employee_id: 'EMP-AZHD-201',
    employee_name: 'Tareq Al Mansoori',
    position: 'Senior Consultant',
    department: 'Regulatory Compliance',
    joining_date: '2022-04-18',
    current_status: 'Active'
  },
  {
    id: 'emp7',
    client_id: 'c2',
    employee_id: 'EMP-AZHD-202',
    employee_name: 'Evelyn Rostova',
    position: 'External Auditor',
    department: 'Quality Assurance',
    joining_date: '2025-01-10',
    current_status: 'Active'
  },
  {
    id: 'emp8',
    client_id: 'c2',
    employee_id: 'EMP-AZHD-203',
    employee_name: 'Omar Al Fayed',
    position: 'System Administrator',
    department: 'IT Services',
    joining_date: '2023-08-20',
    last_working_date: '2026-04-01',
    current_status: 'Terminated'
  },
  {
    id: 'emp-sprc-01',
    client_id: 'SPRC',
    employee_id: 'SPRC-01',
    employee_name: 'Raziya Aseef',
    position: 'Manager',
    department: 'Admin',
    joining_date: '2024-01-01',
    current_status: 'Active'
  }
];
